INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nicobar','',1228);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'North Middle Andaman','',1228);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'South Andaman','',1228);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Anantapur','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chittoor','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'East Godavari','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Guntur','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kadapa','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Krishna','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kurnool','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nellore','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Prakasam','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Srikakulam','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Visakhapatnam','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Vizianagaram','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'West Godavari','',1202);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Anjaw','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Central Siang','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Changlang','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dibang Valley','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'East Kameng','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'East Siang','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kra Daadi','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kurung Kumey','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lohit','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Longding','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lower Dibang Valley','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lower Siang','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lower Subansiri','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Namsai','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Papum Pare','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tawang','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tirap','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Upper Siang','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Upper Subansiri','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'West Kameng','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'West Siang','',1203);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Baksa','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Barpeta','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Biswanath','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bongaigaon','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Cachar','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Charaideo','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chirang','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Darrang','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dhemaji','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dhubri','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dibrugarh','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dima Hasao','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Goalpara','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Golaghat','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hailakandi','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hojai','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jorhat','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kamrup','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kamrup Metropolitan','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Karbi Anglong','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Karimganj','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kokrajhar','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lakhimpur','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Majuli','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Morigaon','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nagaon','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nalbari','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sivasagar','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sonitpur','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'South Salmara-Mankachar','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tinsukia','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Udalguri','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'West Karbi Anglong','',1204);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Araria','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Arwal','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Aurangabad','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Banka','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Begusarai','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bhagalpur','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bhojpur','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Buxar','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Darbhanga','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'East Champaran','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gaya','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gopalganj','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jamui','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jehanabad','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kaimur','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Katihar','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Khagaria','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kishanganj','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lakhisarai','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Madhepura','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Madhubani','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Munger','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Muzaffarpur','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nalanda','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nawada','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Patna','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Purnia','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rohtas','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Saharsa','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Samastipur','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Saran','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sheikhpura','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sheohar','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sitamarhi','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Siwan','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Supaul','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Vaishali','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'West Champaran','',1205);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chandigarh','',10321);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Balod','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Baloda Bazar','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Balrampur','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bastar','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bemetara','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bijapur','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bilaspur','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dantewada','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dhamtari','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Durg','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gariaband','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Janjgir Champa','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jashpur','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kabirdham','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kanker','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kondagaon','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Korba','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Koriya','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mahasamund','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mungeli','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Narayanpur','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Raigarh','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Raipur','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rajnandgaon','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sukma','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Surajpur','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Surguja','',1206);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dadra Nagar Haveli','',1229);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Daman','',1230);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Diu','',1230);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Central Delhi','',1231);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'East Delhi','',1231);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'New Delhi','',1231);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'North Delhi','',1231);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'North East Delhi','',1231);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'North West Delhi','',1231);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Shahdara','',1231);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'South Delhi','',1231);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'South East Delhi','',1231);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'South West Delhi','',1231);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'West Delhi','',1231);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'North Goa','',1207);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'South Goa','',1207);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ahmedabad','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Amreli','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Anand','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Aravalli','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Banaskantha','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bharuch','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bhavnagar','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Botad','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chhota Udaipur','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dahod','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dang','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Devbhoomi Dwarka','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gandhinagar','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gir Somnath','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jamnagar','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Junagadh','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kheda','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kutch','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mahisagar','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mehsana','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Morbi','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Narmada','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Navsari','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Panchmahal','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Patan','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Porbandar','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rajkot','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sabarkantha','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Surat','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Surendranagar','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tapi','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Vadodara','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Valsad','',1208);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ambala','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bhiwani','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Charkhi Dadri','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Faridabad','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Fatehabad','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gurugram *','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hisar','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jhajjar','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jind','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kaithal','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Karnal','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kurukshetra','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mahendragarh','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mewat','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Palwal','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Panchkula','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Panipat','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rewari','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rohtak','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sirsa','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sonipat','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Yamunanagar','',1209);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bilaspur','',1210);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chamba','',1210);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hamirpur','',1210);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kangra','',1210);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kinnaur','',1210);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kullu','',1210);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lahaul Spiti','',1210);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mandi','',1210);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Shimla','',1210);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sirmaur','',1210);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Solan','',1210);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Una','',1210);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Anantnag','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bandipora','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Baramulla','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Budgam','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Doda','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ganderbal','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jammu','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kargil','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kathua','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kishtwar','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kulgam','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kupwara','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Leh','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Poonch','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pulwama','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rajouri','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ramban','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Reasi','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Samba','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Shopian','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Srinagar','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Udhampur','',1211);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bokaro','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chatra','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Deoghar','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dhanbad','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dumka','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'East Singhbhum','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Garhwa','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Giridih','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Godda','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gumla','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hazaribagh','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jamtara','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Khunti','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Koderma','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Latehar','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lohardaga','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pakur','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Palamu','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ramgarh','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ranchi','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sahebganj','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Seraikela Kharsawan','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Simdega','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'West Singhbhum','',1212);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bagalkot','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bangalore Rural','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bangalore Urban','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Belgaum','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bellary','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bidar','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chamarajanagar','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chikkaballapur','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chikkamagaluru','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chitradurga','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dakshina Kannada','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Davanagere','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dharwad','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gadag','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gulbarga','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hassan','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Haveri','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kodagu','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kolar','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Koppal','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mandya','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mysore','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Raichur','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ramanagara','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Shimoga','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tumkur','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Udupi','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Uttara Kannada','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Vijayapura *','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Yadgir','',1201);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Alappuzha','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ernakulam','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Idukki','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kannur','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kasaragod','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kollam','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kottayam','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kozhikode','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Malappuram','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Palakkad','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pathanamthitta','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Thiruvananthapuram','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Thrissur','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Wayanad','',1213);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lakshadweep','',1232);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Agar Malwa','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Alirajpur','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Anuppur','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ashoknagar','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Balaghat','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Barwani','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Betul','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bhind','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bhopal','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Burhanpur','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chhatarpur','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chhindwara','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Damoh','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Datia','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dewas','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dhar','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dindori','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Guna','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gwalior','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Harda','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hoshangabad','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Indore','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jabalpur','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jhabua','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Katni','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Khandwa','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Khargone','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mandla','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mandsaur','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Morena','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Narsinghpur','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Neemuch','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Panna','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Raisen','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rajgarh','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ratlam','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rewa','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sagar','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Satna','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sehore','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Seoni','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Shahdol','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Shajapur','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sheopur','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Shivpuri','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sidhi','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Singrauli','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tikamgarh','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ujjain','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Umaria','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Vidisha','',1214);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ahmednagar','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Akola','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Amravati','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Aurangabad','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Beed','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bhandara','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Buldhana','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chandrapur','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dhule','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gadchiroli','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gondia','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hingoli','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jalgaon','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jalna','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kolhapur','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Latur','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mumbai City','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mumbai Suburban','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nagpur','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nanded','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nandurbar','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nashik','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Osmanabad','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Palghar','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Parbhani','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pune','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Raigad','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ratnagiri','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sangli','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Satara','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sindhudurg','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Solapur','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Thane','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Wardha','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Washim','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Yavatmal','',1200);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bishnupur','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chandel','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Churachandpur','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Imphal East','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Imphal West','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jiribam','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kakching','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kamjong','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kangpokpi','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Noney','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pherzawl','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Senapati','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tamenglong','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tengnoupal','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Thoubal','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ukhrul','',1215);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'East Garo Hills','',1216);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'East Jaintia Hills','',1216);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'East Khasi Hills','',1216);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'North Garo Hills','',1216);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ri Bhoi','',1216);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'South Garo Hills','',1216);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'South West Garo Hills','',1216);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'South West Khasi Hills','',1216);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'West Garo Hills','',1216);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'West Jaintia Hills','',1216);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'West Khasi Hills','',1216);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Aizawl','',1217);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Champhai','',1217);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kolasib','',1217);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lawngtlai','',1217);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lunglei','',1217);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mamit','',1217);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Saiha','',1217);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Serchhip','',1217);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dimapur','',1218);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kiphire','',1218);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kohima','',1218);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Longleng','',1218);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mokokchung','',1218);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mon','',1218);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Peren','',1218);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Phek','',1218);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tuensang','',1218);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Wokha','',1218);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Zunheboto','',1218);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Angul','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Balangir','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Balasore','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bargarh','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bhadrak','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Boudh','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Cuttack','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Debagarh','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dhenkanal','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gajapati','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ganjam','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jagatsinghpur','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jajpur','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jharsuguda','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kalahandi','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kandhamal','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kendrapara','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kendujhar','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Khordha *','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Koraput','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Malkangiri','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mayurbhanj','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nabarangpur','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nayagarh','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nuapada','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Puri','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rayagada','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sambalpur','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Subarnapur','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sundergarh','',1219);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Karaikal','',1233);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mahe','',1233);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Puducherry','',1233);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Yanam','',1233);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Amritsar','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Barnala','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bathinda','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Faridkot','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Fatehgarh Sahib','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Fazilka','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Firozpur','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gurdaspur','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hoshiarpur','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jalandhar','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kapurthala','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ludhiana','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mansa','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Moga','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mohali','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Muktsar','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pathankot','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Patiala','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rupnagar','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sangrur','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Shaheed Bhagat Singh Nagar','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tarn Taran','',1220);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ajmer','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Alwar','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Banswara','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Baran','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Barmer','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bharatpur','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bhilwara','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bikaner','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bundi','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chittorgarh','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Churu','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dausa','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dholpur','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dungarpur','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ganganagar','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hanumangarh','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jaipur','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jaisalmer','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jalore','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jhalawar','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jhunjhunu','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jodhpur','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Karauli','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kota','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nagaur','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pali','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pratapgarh','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rajsamand','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sawai Madhopur','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sikar','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sirohi','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tonk','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Udaipur','',1221);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'East Sikkim','',1222);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'North Sikkim','',1222);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'South Sikkim','',1222);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'West Sikkim','',1222);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ariyalur','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chennai','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Coimbatore','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Cuddalore','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dharmapuri','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dindigul','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Erode','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kanchipuram','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kanyakumari','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Karur','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Krishnagiri','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Madurai','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nagapattinam','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Namakkal','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nilgiris','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Perambalur','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pudukkottai','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ramanathapuram','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Salem','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sivaganga','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Thanjavur','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Theni','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Thoothukudi','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tiruchirappalli','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tirunelveli','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tiruppur','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tiruvallur','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tiruvannamalai','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tiruvarur','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Vellore','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Viluppuram','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Virudhunagar','',1223);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Adilabad','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bhadradri Kothagudem','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hyderabad','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jagtial','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jangaon','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jayashankar Bhupalpally','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jogulamba Gadwal','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kamareddy','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Karimnagar','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Khammam','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Komaram Bheem','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mahabubabad','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mahbubnagar','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mancherial','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Medak','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Medchal','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nagarkurnool','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nalgonda','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nirmal','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nizamabad','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Peddapalli','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rajanna Sircilla','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ranga Reddy','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sangareddy','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Siddipet','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Suryapet','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Vikarabad','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Wanaparthy','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Warangal Rural','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Warangal Urban','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Yadadri Bhuvanagiri','',10267);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dhalai','',1224);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gomati','',1224);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Khowai','',1224);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'North Tripura','',1224);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sepahijala','',1224);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'South Tripura','',1224);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Unakoti','',1224);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'West Tripura','',1224);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Agra','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Aligarh','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ambedkar Nagar','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Amethi *','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Amroha *','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Auraiya','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ayodhya *','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Azamgarh','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Baghpat','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bahraich','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ballia','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Balrampur Ramanujganj *','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Banda','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Barabanki','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bareilly','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Basti','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bhadohi','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bijnor','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Budaun','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bulandshahr','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chandauli','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chitrakoot','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Deoria','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Etah','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Etawah','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Farrukhabad','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Fatehpur','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Firozabad','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gautam Buddha Nagar','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ghaziabad','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Ghazipur','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gonda','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Gorakhpur','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hamirpur','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hapur *','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hardoi','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hathras *','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jalaun','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jaunpur','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jhansi','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kannauj','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kanpur Dehat *','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kanpur Nagar','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kasganj *','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kaushambi','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kheri','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kushinagar','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lalitpur','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Lucknow','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Maharajganj','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mahoba','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mainpuri','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mathura','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mau','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Meerut','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Mirzapur','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Moradabad','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Muzaffarnagar','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pilibhit','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pratapgarh','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Prayag Raj*','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Raebareli','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rampur','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Saharanpur','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sambhal *','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sant Kabir Nagar','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Shahjahanpur','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Shamli *','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Shravasti','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Siddharthnagar','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sitapur','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sonbhadra','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Sultanpur','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Unnao','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Varanasi','',1226);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Almora','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bageshwar','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Chamoli','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Champawat','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dehradun','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Haridwar','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nainital','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pauri','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Pithoragarh','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Rudraprayag','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Tehri','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Udham Singh Nagar','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Uttarkashi','',1225);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Alipurduar','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Bankura','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Birbhum','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Cooch Behar','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Dakshin Dinajpur','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Darjeeling','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Hooghly','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Howrah','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jalpaiguri','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Jhargram','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kalimpong','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Kolkata','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Malda','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Murshidabad','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Nadia','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'North 24 Parganas','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Paschim Bardhaman','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Paschim Medinipur','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Purba Bardhaman','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Purba Medinipur','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Purulia','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'South 24 Parganas','',1227);
INSERT INTO `civicrm_county` (`id`, `name`, `abbreviation`, `state_province_id`) VALUES (NULL,'Uttar Dinajpur','',1227);
